{% set org = "scikit-beam" %}
{% set name = "rixs" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}/
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python

  run:
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - rixs.process2d

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: BSD 3-clause
