{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="1" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - analysis >=2019C1.1
    - caproto >=0.2.3
    - nslsii >=0.0.7
    - pyepics >=3.3.0
    - pyolog >=4.4.0
    - pyserial
