{% set year = "2018" %}
{% set cycle = "3" %}
{% set version ="1" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - analysis >=2018C3.1
    - caproto >=0.1.2
    - nslsii >=0.0.6
    - pyepics >=3.3.0
    - pyolog >=4.4.0
    - pyserial
