{% set version = "0.1.14" %}

package:
  name: csxtools
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II-CSX/csxtools/
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - pytest
    - python
    - numpy
    - setuptools

  run:
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - pims >=0.3.3
    - python
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
    - pytest
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD 3-clause
