{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - hkl
    - hklpy >=0.3.13
    - 23-id-1-csx1-analysis
    - hxntools
