{% set year = "2018" %}
{% set cycle = "3" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - gsl
    - libiconv
    - pcre
    - hkl
    - hklpy >=0.3.12
    - 23-id-1-csx1-analysis
    - hxntools
    - pygobject >=3.28.*
    - gobject-inrospection >=1.56.*
