{% set version = "5.0.0.2173" %}

package:
  name: hkl
  version: {{ version }}

source:
  git_url: https://github.com/picca/hkl
  git_rev: v{{ version }}

build:
  number: 6
  skip: True # [py2k]

requirements:
  build:
    - autoconf
    - automake
    - gobject-introspection
    - gsl
    - libtool
    - m4
    - pkg-config
    - pygobject
    - python
  run:
    - gsl
    - libiconv
    - numpy
    - pcre
    - pygobject  # [py3k]
    - python

about:
  home: http://repo.or.cz/w/hkl.git/
  license: LGPL
