{% set version = "2.9.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: 49d593c07a3a4cb87ed421f502e34368b98282a4ac6d4388379aab80b11c7924

build:
  number: 1000

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy
    - hdf5
    - cython
    - six
    - pkgconfig
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - six
    - unittest2  # [py26 or py27]
    - pyreadline  # [win]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - ocefpaf
