{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="1" %}

package:
  name: 18-id-fxi-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - pypdf2
    - reportlab
    - tomopy
