{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 04-id-isr-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - hkl
    - hklpy >=0.3.13
    - eiger-io
    - 04-id-isr-analysis
