{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - csxtools 0.1.13
