{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 04-id-isr-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - eiger-io
