{% set name = "zsh" %}
{% set version = "5.6.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/zsh-users/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
    patches:
        - utils.c.patch

build:
    number: 0

requirements:
    build:
        - gcc

about:
    home: http://www.zsh.org
    license: Custom
    license_url: https://github.com/zsh-users/zsh/blob/master/LICENCE
    summary: The Z shell (zsh)
