{% set version = "0.3.13" %}

package:
  name: hklpy
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/hklpy
  git_rev: v{{ version }}

build:
  number: 0
  skip: True # [py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - hkl
    - numpy
    - ophyd
    - pygobject
    - python

test:
  imports:
    - hkl
    - hkl.calc
    - hkl.context
    - hkl.diffract
    - hkl.engine
    - hkl.sample
    - hkl.util

about:
  home: https://github.com/NSLS-II/hklpy
  license: BSD 3-Clause
  summary: >
    Diffractometer computation library with ophyd pseudopositioner support

extra:
 recipe-maintainers:
  - ericdill
  - licode
  - mrakitin
  - tacaswell
